const phrases = [
  "Signs point to yes, but don't hold your breath.",
  'Absolutely, without a shadow of a doubt!',
  'My sources say nope, not happening.',
  'Yes, and the stars are aligned in your favor.',
  'Outlook not so good, try again later.',
  'Yes, but only if you believe hard enough.',
  "Without a doubt, you've got this!",
  'My gut says no, sorry.',
  'Yes, but with a side of caution.',
  'Absolutely not, no way, no how.',
  'Most likely, but prepare for a twist.',
  'My sources say no, better luck next time.',
  'Yes, and the universe is cheering you on.',
  'Not looking good, try a different approach.',
  'Yes, but not without some effort.',
  'Definitely not, time to reconsider.',
  "Yes, but don't get too comfortable.",
  'Signs point to no, sorry.',
  "It's a yes, but keep your eyes open for surprises.",
  "No, and it's time to move on.",
  'Outlook good, but stay on your toes.',
  'Nope, not happening, try something else.',
  'Yes, but with a twist of fate.',
  'My sources say no, time to rethink.',
  "Yes, but only if you're willing to take a risk.",
  'Absolutely not, better luck next time.',
  'Yes, but with a hint of uncertainty.',
  'My gut says no, find another path.',
  "Yes, but only if you're prepared for the consequences.",
  'Not likely, but stranger things have happened.',
  'Yes, but with a sprinkle of doubt.',
  "No, and it's time to let it go.",
  "Signs point to yes, but don't get too comfortable.",
  'Absolutely, without a doubt, go for it!',
  'My sources say no, time to reassess.',
  'Yes, but not without a few obstacles.',
  'Outlook not so good, try a different approach.',
  'Yes, but with a dash of uncertainty.',
  'Definitely not, time to rethink your strategy.',
  'Yes, but be prepared for a bumpy ride.',
  'Most likely, but be cautious.',
  'My gut says no, try another route.',
  "Yes, but only if you're willing to put in the work.",
  'Not looking good, try a different angle.',
  'Yes, but with a twist of fate.',
  'Signs point to no, sorry.',
  "It's a yes, but with a catch.",
  "No, and it's time to move on.",
  'Yes, but with a hint of doubt.',
  "Outlook good, but don't get ahead of yourself.",
  'Nope, not happening, try something else.',
  'Yes, but with a side of caution.',
  'Absolutely not, time to reconsider.',
  'Yes, but with a sprinkle of uncertainty.',
  'My sources say no, better luck next time.',
  "Yes, but only if you're willing to take a risk.",
  'Not likely, but stranger things have happened.',
  'Yes, but with a hint of doubt.',
  "No, and it's time to let it go.",
  'Absolutely, go for it with all your might!',
  'My gut says no, find another path.',
  'Yes, but with a twist of fate.',
  'Most likely, but be prepared for surprises.',
  'Yes, but with a sprinkle of uncertainty.',
  'Outlook not so good, try a different approach.',
  "Yes, but only if you're willing to put in the effort.",
  'Definitely not, time to rethink your strategy.',
  'Yes, but be prepared for the unexpected.',
  'My sources say no, time to reassess.',
  'Yes, but with a dash of uncertainty.',
  "It's a yes, but with a twist.",
  "No, and it's time to move on.",
  'Yes, but with a hint of doubt.',
  "Signs point to yes, but don't celebrate yet.",
  'Absolutely not, better luck next time.',
  'Yes, but with a side of caution.',
  'My gut says no, try another route.',
  "Yes, but only if you're willing to face the challenges.",
  'Not looking good, try a different angle.',
  'Yes, but with a twist of fate.',
  'Most likely, but be prepared for hurdles.',
  'Yes, but with a sprinkle of doubt.',
  "Outlook good, but don't let your guard down.",
  'Nope, not happening, try something else.',
  'Yes, but with a hint of uncertainty.',
  'Absolutely not, time to reconsider.',
  "Yes, but only if you're willing to take a leap of faith.",
  'My sources say no, better luck next time.',
  'Yes, but with a pinch of caution.',
  'Not likely, but miracles do happen.',
  'Yes, but with a hint of doubt.',
  "No, and it's time to let it go.",
  'Definitely, go for it without hesitation!',
  'My gut says no, find another path.',
  'Yes, but with a twist of fate.',
  'Most likely, but be prepared for twists.',
  'Yes, but with a sprinkle of uncertainty.',
  'Outlook not so good, try a different approach.',
  "Yes, but only if you're willing to put in the work.",
  'Definitely not, time to rethink your strategy.',
];

export default phrases;
